version: "3"

services:
  db:
    container_name: ng_api_db
    image: postgres:14.2-alpine
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ng-cash

networks:
  default:
    name: ng_api_net